-- ============================================================
-- LIPA CITY COLLEGES — Payroll System — Supabase / PostgreSQL
-- Paste this whole file into Supabase Dashboard > SQL Editor > New query > Run.
-- Safe to re-run: IF NOT EXISTS / ON CONFLICT everywhere, no DROP TABLE.
--
-- Project: https://htlbmhkseweclwlixzlz.supabase.co
--
-- Contains every table the system needs:
--   admins (superadmin/finance/hr + is_active),
--   app_settings, departments (6 LCC colleges), positions (academic titles),
--   employees (portal password + photo), attendance,
--   employee_references, payroll_records.
--
-- Seed logins after import:
--   Admin:           username `admin` / password `admin123` (change ASAP)
--                    hash below = password_hash('admin123')
--   Employee portal: Employee No `25-0001` / password `Employee@123`
--
-- MySQL -> PostgreSQL mapping:
--   INT AUTO_INCREMENT     -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--   ENUM(...)              -> VARCHAR + CHECK (...)
--   TIMESTAMP ON UPDATE .. -> TIMESTAMPTZ + updated_at trigger (bottom)
--   ON DUPLICATE KEY UPDATE-> ON CONFLICT ...
-- ============================================================

-- ------------------------------------------------------------
-- 0. Helper replacing MySQL's ON UPDATE CURRENT_TIMESTAMP
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- 1. ADMINS (superadmin kept)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admins (
    admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'superadmin'
        CHECK (role IN ('superadmin', 'finance', 'hr')),
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Backfill for databases created by the old supabase_schema.sql (no role cols)
ALTER TABLE public.admins ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'superadmin';
ALTER TABLE public.admins ADD COLUMN IF NOT EXISTS is_active INTEGER NOT NULL DEFAULT 1;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'admins_role_check'
    ) THEN
        ALTER TABLE public.admins
            ADD CONSTRAINT admins_role_check CHECK (role IN ('superadmin', 'finance', 'hr'));
    END IF;
END $$;

-- Default superadmin: admin / admin123 — CHANGE AFTER FIRST LOGIN
-- (hash generated with PHP password_hash('admin123', PASSWORD_DEFAULT))
INSERT INTO public.admins
    (admin_id, username, password_hash, full_name, role, is_active, created_at)
VALUES
    (1, 'admin',
     '$2y$10$cK4PFcHW5dXRAMOZuTb2GeBosLrZWt7WSfV7NACSSFcfZPo.PbWHK',
     'System Administrator',
     'superadmin', 1,
     NOW())
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- 2. APP SETTINGS (Lipa City Colleges branding)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_settings (
    setting_key VARCHAR(80) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL DEFAULT ''
);

INSERT INTO public.app_settings (setting_key, setting_value) VALUES
('company_name', 'Lipa City Colleges'),
('company_address', 'Lipa City, Batangas'),
('employee_number_digits', '4'),
('employee_number_prefix', '25')
ON CONFLICT (setting_key) DO NOTHING;

-- Upgrade brand on databases seeded as Paywise before
UPDATE public.app_settings SET setting_value = 'Lipa City Colleges'
WHERE setting_key = 'company_name' AND setting_value = 'Paywise';

-- ------------------------------------------------------------
-- 3. DEPARTMENTS — 6 LCC colleges
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(150) NOT NULL UNIQUE,
    department_code VARCHAR(30) UNIQUE,
    description TEXT,
    status VARCHAR(10) NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_department_status ON public.departments (status);

INSERT INTO public.departments
    (department_id, department_name, department_code, description, status, created_at, updated_at)
VALUES
(1, 'College of Computing Technology and Engineering', 'CCTE',
 'College of Computing Technology and Engineering', 'Active', NOW(), NOW()),
(2, 'College of Nursing', 'CON',
 'College of Nursing', 'Active', NOW(), NOW()),
(3, 'College of Internal and Tourism Management', 'CITM',
 'College of Internal and Tourism Management', 'Active', NOW(), NOW()),
(4, 'College of Criminal Justice Education', 'CCJE',
 'College of Criminal Justice Education', 'Active', NOW(), NOW()),
(5, 'College of Business Accountancy', 'CBA',
 'College of Business Accountancy', 'Active', NOW(), NOW()),
(6, 'College of Education and Liberal Arts', 'CELA',
 'College of Education and Liberal Arts', 'Active', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Heal corporate-seeded databases back to LCC names (by id + by name)
UPDATE public.departments SET department_name='College of Computing Technology and Engineering', department_code='CCTE', description='College of Computing Technology and Engineering', status='Active' WHERE department_id=1;
UPDATE public.departments SET department_name='College of Nursing', department_code='CON', description='College of Nursing', status='Active' WHERE department_id=2;
UPDATE public.departments SET department_name='College of Internal and Tourism Management', department_code='CITM', description='College of Internal and Tourism Management', status='Active' WHERE department_id=3;
UPDATE public.departments SET department_name='College of Criminal Justice Education', department_code='CCJE', description='College of Criminal Justice Education', status='Active' WHERE department_id=4;
UPDATE public.departments SET department_name='College of Business Accountancy', department_code='CBA', description='College of Business Accountancy', status='Active' WHERE department_id=5;
UPDATE public.departments SET department_name='College of Education and Liberal Arts', department_code='CELA', description='College of Education and Liberal Arts', status='Active' WHERE department_id=6;

-- ------------------------------------------------------------
-- 4. POSITIONS — academic titles per college
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.positions (
    position_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL,
    position_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_department_position UNIQUE (department_id, position_name),
    CONSTRAINT fk_position_department
        FOREIGN KEY (department_id)
        REFERENCES public.departments (department_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_position_department ON public.positions (department_id);

-- Rebuild only when the table is still corporate/empty-shaped:
-- delete corporate titles, then insert academic list (idempotent guard below).
DELETE FROM public.positions
WHERE position_name IN ('Operations Manager','Supervisor','Team Lead','Assistant','Finance Manager','Payroll Officer','HR Manager','HR Officer','Recruiter','IT Manager','Developer','Support Specialist','Sales Manager','Sales Officer','Marketing Officer','Support Manager','Support Agent');

INSERT INTO public.positions (position_id, department_id, position_name, created_at) VALUES
(1,1,'Dean',NOW()),
(2,1,'Department Head',NOW()),
(3,1,'Coordinator',NOW()),
(4,1,'Professor',NOW()),
(5,1,'Associate Professor',NOW()),
(6,1,'Assistant Professor',NOW()),
(7,1,'Instructor',NOW()),
(8,1,'Lecturer',NOW()),
(9,1,'Staff',NOW()),
(10,1,'Administrative Staff',NOW()),
(11,1,'Laboratory Staff',NOW()),
(12,1,'Technician',NOW()),
(13,1,'IT Staff',NOW()),
(14,2,'Dean',NOW()),
(15,2,'Department Head',NOW()),
(16,2,'Coordinator',NOW()),
(17,2,'Professor',NOW()),
(18,2,'Associate Professor',NOW()),
(19,2,'Assistant Professor',NOW()),
(20,2,'Instructor',NOW()),
(21,2,'Lecturer',NOW()),
(22,2,'Clinical Instructor',NOW()),
(23,2,'Staff',NOW()),
(24,2,'Administrative Staff',NOW()),
(25,2,'Laboratory Staff',NOW()),
(26,3,'Dean',NOW()),
(27,3,'Department Head',NOW()),
(28,3,'Coordinator',NOW()),
(29,3,'Professor',NOW()),
(30,3,'Associate Professor',NOW()),
(31,3,'Assistant Professor',NOW()),
(32,3,'Instructor',NOW()),
(33,3,'Lecturer',NOW()),
(34,3,'Staff',NOW()),
(35,3,'Administrative Staff',NOW()),
(36,4,'Dean',NOW()),
(37,4,'Department Head',NOW()),
(38,4,'Coordinator',NOW()),
(39,4,'Professor',NOW()),
(40,4,'Associate Professor',NOW()),
(41,4,'Assistant Professor',NOW()),
(42,4,'Instructor',NOW()),
(43,4,'Lecturer',NOW()),
(44,4,'Staff',NOW()),
(45,4,'Administrative Staff',NOW()),
(46,5,'Dean',NOW()),
(47,5,'Department Head',NOW()),
(48,5,'Coordinator',NOW()),
(49,5,'Professor',NOW()),
(50,5,'Associate Professor',NOW()),
(51,5,'Assistant Professor',NOW()),
(52,5,'Instructor',NOW()),
(53,5,'Lecturer',NOW()),
(54,5,'Staff',NOW()),
(55,5,'Administrative Staff',NOW()),
(56,5,'Accountant',NOW()),
(57,6,'Dean',NOW()),
(58,6,'Department Head',NOW()),
(59,6,'Coordinator',NOW()),
(60,6,'Professor',NOW()),
(61,6,'Associate Professor',NOW()),
(62,6,'Assistant Professor',NOW()),
(63,6,'Instructor',NOW()),
(64,6,'Lecturer',NOW()),
(65,6,'Staff',NOW()),
(66,6,'Administrative Staff',NOW())
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- 5. EMPLOYEES (portal_password included)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.employees (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no VARCHAR(20) NOT NULL UNIQUE,
    portal_password VARCHAR(255),
    photo_path VARCHAR(255),

    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,

    gender VARCHAR(10) NOT NULL DEFAULT 'Other'
        CHECK (gender IN ('Male', 'Female', 'Other')),
    birth_date DATE,
    contact_number VARCHAR(20),
    email VARCHAR(100),
    civil_status VARCHAR(30),
    nationality VARCHAR(50),
    religion VARCHAR(50),

    permanent_address TEXT,
    present_address TEXT,

    sss_no VARCHAR(30),
    philhealth_no VARCHAR(30),
    pagibig_no VARCHAR(30),
    tin_no VARCHAR(30),
    atm_no VARCHAR(40),

    department VARCHAR(150),
    position VARCHAR(120),
    employment_status VARCHAR(20) NOT NULL DEFAULT 'Regular'
        CHECK (employment_status IN ('Regular', 'Probationary', 'Contractual', 'Part-Time')),

    basic_salary NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    date_hired DATE,

    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(30),
    emergency_contact_address TEXT,

    dependent_name VARCHAR(100),
    dependent_relationship VARCHAR(50),
    dependent_birth_date DATE,

    education_background TEXT,
    character_reference TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_employee_department ON public.employees (department);
CREATE INDEX IF NOT EXISTS idx_employee_status ON public.employees (employment_status);
CREATE INDEX IF NOT EXISTS idx_employee_name ON public.employees (last_name, first_name);

ALTER TABLE public.employees
    ADD COLUMN IF NOT EXISTS portal_password VARCHAR(255);

-- SAMPLE EMPLOYEE PORTAL ACCOUNT
-- Employee No: 25-0001 / Password: Employee@123
INSERT INTO public.employees
    (employee_no, portal_password, first_name, middle_name, last_name, gender, email, department, position, employment_status, basic_salary, date_hired)
VALUES
    ('25-0001', '$2y$12$RgvcOSwmrocDtSEbbT2zFO6V5mgTwm4Q12Vj7jg5TKIAPnJ0rjngG', 'Juan', 'D.', 'Dela Cruz', 'Male', 'juan.delacruz@example.com', 'College of Computing Technology and Engineering', 'Instructor', 'Regular', 25000.00, '2026-06-01')
ON CONFLICT (employee_no) DO UPDATE
    SET portal_password = EXCLUDED.portal_password;

-- Remap corporate free-text back to LCC colleges (for converted DBs)
UPDATE public.employees SET department='College of Computing Technology and Engineering' WHERE department='Information Technology';
UPDATE public.employees SET department='College of Nursing' WHERE department='Customer Support';
UPDATE public.employees SET department='College of Internal and Tourism Management' WHERE department='Sales & Marketing';
UPDATE public.employees SET department='College of Criminal Justice Education' WHERE department='Operations';
UPDATE public.employees SET department='College of Business Accountancy' WHERE department='Finance & Accounting';
UPDATE public.employees SET department='College of Education and Liberal Arts' WHERE department='Human Resources';

-- ------------------------------------------------------------
-- 6. ATTENDANCE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance (
    attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    attendance_date DATE NOT NULL,
    time_in TIME,
    time_out TIME,
    status VARCHAR(10) NOT NULL DEFAULT 'Present'
        CHECK (status IN ('Present', 'Late', 'Absent', 'On Leave', 'Half Day')),
    remarks VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_employee_attendance_date UNIQUE (employee_id, attendance_date),
    CONSTRAINT fk_attendance_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance (attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_status ON public.attendance (status);

-- ------------------------------------------------------------
-- 7. EMPLOYEE REFERENCES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.employee_references (
    reference_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    reference_name VARCHAR(120) NOT NULL,
    reference_address TEXT,
    reference_occupation VARCHAR(100),
    reference_contact_number VARCHAR(40),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reference_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reference_employee ON public.employee_references (employee_id);

-- ------------------------------------------------------------
-- 8. PAYROLL RECORDS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payroll_records (
    payroll_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,

    period_start DATE NOT NULL,
    period_end DATE NOT NULL,

    basic_salary NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    allowances NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    other_earnings NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    deductions NUMERIC(12,2) NOT NULL DEFAULT 0.00,

    gross_pay NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    net_pay NUMERIC(12,2) NOT NULL DEFAULT 0.00,

    status VARCHAR(10) NOT NULL DEFAULT 'Draft'
        CHECK (status IN ('Draft', 'Approved', 'Paid')),
    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_payroll_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_payroll_employee ON public.payroll_records (employee_id);
CREATE INDEX IF NOT EXISTS idx_payroll_period ON public.payroll_records (period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_payroll_status ON public.payroll_records (status);

-- ------------------------------------------------------------
-- 9. updated_at auto-update triggers
-- ------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_departments_updated_at ON public.departments;
CREATE TRIGGER trg_departments_updated_at
    BEFORE UPDATE ON public.departments
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_employees_updated_at ON public.employees;
CREATE TRIGGER trg_employees_updated_at
    BEFORE UPDATE ON public.employees
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_attendance_updated_at ON public.attendance;
CREATE TRIGGER trg_attendance_updated_at
    BEFORE UPDATE ON public.attendance
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_employee_references_updated_at ON public.employee_references;
CREATE TRIGGER trg_employee_references_updated_at
    BEFORE UPDATE ON public.employee_references
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_payroll_records_updated_at ON public.payroll_records;
CREATE TRIGGER trg_payroll_records_updated_at
    BEFORE UPDATE ON public.payroll_records
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ------------------------------------------------------------
-- 10. Sequence reset (new inserts continue after seeded IDs)
-- ------------------------------------------------------------
SELECT setval(
    pg_get_serial_sequence('public.admins', 'admin_id'),
    GREATEST(COALESCE((SELECT MAX(admin_id) FROM public.admins), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.departments', 'department_id'),
    GREATEST(COALESCE((SELECT MAX(department_id) FROM public.departments), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.positions', 'position_id'),
    GREATEST(COALESCE((SELECT MAX(position_id) FROM public.positions), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.employees', 'employee_id'),
    GREATEST(COALESCE((SELECT MAX(employee_id) FROM public.employees), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.employee_references', 'reference_id'),
    GREATEST(COALESCE((SELECT MAX(reference_id) FROM public.employee_references), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.attendance', 'attendance_id'),
    GREATEST(COALESCE((SELECT MAX(attendance_id) FROM public.attendance), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.payroll_records', 'payroll_id'),
    GREATEST(COALESCE((SELECT MAX(payroll_id) FROM public.payroll_records), 1), 1)
);

-- NOTE: Row Level Security is intentionally NOT enabled so the PHP app's
-- direct Postgres connection keeps working. If you use the Supabase REST API
-- with the publishable key, enable RLS and add policies per table.
-- Done.
