-- ============================================================
-- LCC PAYROLL SYSTEM — PostgreSQL / Supabase schema
-- Converted from MySQL: schema.sql + attendance_portal.sql
--   + employee_portal.sql (all three folded into this one file)
--
-- SAFE FOR AN EXISTING DATABASE: no DROP TABLE anywhere.
-- Everything is IF NOT EXISTS / ON CONFLICT, so you can
-- run it and re-run it safely in Supabase SQL Editor.
--
-- How to use:
--   1. Supabase Dashboard > SQL Editor > New query.
--   2. Paste this whole file > Run.
--
-- MySQL -> PostgreSQL mapping used:
--   INT AUTO_INCREMENT       -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--   ENUM(...)                -> VARCHAR + CHECK (...) (no custom types needed)
--   TIMESTAMP ON UPDATE ...  -> TIMESTAMPTZ + updated_at trigger (see bottom)
--   ENGINE/CHARSET/COLLATE   -> removed (not applicable in Postgres)
--   ON DUPLICATE KEY UPDATE  -> ON CONFLICT ...
--   ALTER TABLE ... AUTO_INCREMENT = N -> setval(...) sequence reset (bottom)
-- ============================================================

-- ------------------------------------------------------------
-- 0. Helper replacing MySQL's ON UPDATE CURRENT_TIMESTAMP
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- 1. ADMINS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admins (
    admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.admins
    (admin_id, username, password_hash, full_name, created_at)
VALUES
    (1, 'admin',
     '$2y$10$cK4PFcHW5dXRAMOZuTb2GeBosLrZWt7WSfV7NACSSFcfZPo.PbWHK',
     'System Administrator',
     '2026-08-13 05:25:14')
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- 2. APP SETTINGS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_settings (
    setting_key VARCHAR(80) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL DEFAULT ''
);

INSERT INTO public.app_settings (setting_key, setting_value) VALUES
('company_address', ''),
('company_name', 'LCC Payroll System'),
('employee_number_digits', '4'),
('employee_number_prefix', '25')
ON CONFLICT (setting_key) DO NOTHING;

-- ------------------------------------------------------------
-- 3. DEPARTMENTS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(150) NOT NULL UNIQUE,
    department_code VARCHAR(30) UNIQUE,
    description TEXT,
    status VARCHAR(10) NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_department_status ON public.departments (status);

INSERT INTO public.departments
    (department_id, department_name, department_code, description, status, created_at, updated_at)
VALUES
(1, 'College of Computing Technology and Engineering', 'CCTE',
 'College of Computing Technology and Engineering', 'Active',
 '2026-09-08 14:56:08', '2026-09-09 08:16:01'),

(2, 'College of Nursing', 'CON',
 'College of Nursing', 'Active',
 '2026-09-08 14:56:08', '2026-09-09 08:16:01'),

(3, 'College of Internal and Tourism Management', 'CITM',
 'College of Internal and Tourism Management', 'Active',
 '2026-09-08 14:56:08', '2026-09-09 08:16:01'),

(4, 'College of Criminal Justice Education', 'CCJE',
 'College of Criminal Justice Education', 'Active',
 '2026-09-08 14:56:08', '2026-09-09 08:16:01'),

(5, 'College of Business Accountancy', 'CBA',
 'College of Business Accountancy', 'Active',
 '2026-09-08 14:56:08', '2026-09-09 08:16:01'),

(6, 'College of Education and Liberal Arts', 'CELA',
 'College of Education and Liberal Arts', 'Active',
 '2026-09-08 14:56:08', '2026-09-09 08:16:01')
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- 4. POSITIONS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.positions (
    position_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL,
    position_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_department_position UNIQUE (department_id, position_name),
    CONSTRAINT fk_position_department
        FOREIGN KEY (department_id)
        REFERENCES public.departments (department_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_position_department ON public.positions (department_id);

INSERT INTO public.positions (position_id, department_id, position_name, created_at) VALUES
(1,1,'Dean','2026-09-08 14:56:08'),
(2,1,'Department Head','2026-09-08 14:56:08'),
(3,1,'Coordinator','2026-09-08 14:56:08'),
(4,1,'Professor','2026-09-08 14:56:08'),
(5,1,'Associate Professor','2026-09-08 14:56:08'),
(6,1,'Assistant Professor','2026-09-08 14:56:08'),
(7,1,'Instructor','2026-09-08 14:56:08'),
(8,1,'Lecturer','2026-09-08 14:56:08'),
(9,1,'Staff','2026-09-08 14:56:08'),
(10,1,'Administrative Staff','2026-09-08 14:56:08'),
(11,1,'Laboratory Staff','2026-09-08 14:56:08'),
(12,1,'Technician','2026-09-08 14:56:08'),
(13,1,'IT Staff','2026-09-08 14:56:08'),

(14,2,'Dean','2026-09-08 14:56:08'),
(15,2,'Department Head','2026-09-08 14:56:08'),
(16,2,'Coordinator','2026-09-08 14:56:08'),
(17,2,'Professor','2026-09-08 14:56:08'),
(18,2,'Associate Professor','2026-09-08 14:56:08'),
(19,2,'Assistant Professor','2026-09-08 14:56:08'),
(20,2,'Instructor','2026-09-08 14:56:08'),
(21,2,'Lecturer','2026-09-08 14:56:08'),
(22,2,'Clinical Instructor','2026-09-08 14:56:08'),
(23,2,'Staff','2026-09-08 14:56:08'),
(24,2,'Administrative Staff','2026-09-08 14:56:08'),
(25,2,'Laboratory Staff','2026-09-08 14:56:08'),

(26,3,'Dean','2026-09-08 14:56:08'),
(27,3,'Department Head','2026-09-08 14:56:08'),
(28,3,'Coordinator','2026-09-08 14:56:08'),
(29,3,'Professor','2026-09-08 14:56:08'),
(30,3,'Associate Professor','2026-09-08 14:56:08'),
(31,3,'Assistant Professor','2026-09-08 14:56:08'),
(32,3,'Instructor','2026-09-08 14:56:08'),
(33,3,'Lecturer','2026-09-08 14:56:08'),
(34,3,'Staff','2026-09-08 14:56:08'),
(35,3,'Administrative Staff','2026-09-08 14:56:08'),

(36,4,'Dean','2026-09-08 14:56:08'),
(37,4,'Department Head','2026-09-08 14:56:08'),
(38,4,'Coordinator','2026-09-08 14:56:08'),
(39,4,'Professor','2026-09-08 14:56:08'),
(40,4,'Associate Professor','2026-09-08 14:56:08'),
(41,4,'Assistant Professor','2026-09-08 14:56:08'),
(42,4,'Instructor','2026-09-08 14:56:08'),
(43,4,'Lecturer','2026-09-08 14:56:08'),
(44,4,'Staff','2026-09-08 14:56:08'),
(45,4,'Administrative Staff','2026-09-08 14:56:08'),

(46,5,'Dean','2026-09-08 14:56:08'),
(47,5,'Department Head','2026-09-08 14:56:08'),
(48,5,'Coordinator','2026-09-08 14:56:08'),
(49,5,'Professor','2026-09-08 14:56:08'),
(50,5,'Associate Professor','2026-09-08 14:56:08'),
(51,5,'Assistant Professor','2026-09-08 14:56:08'),
(52,5,'Instructor','2026-09-08 14:56:08'),
(53,5,'Lecturer','2026-09-08 14:56:08'),
(54,5,'Staff','2026-09-08 14:56:08'),
(55,5,'Administrative Staff','2026-09-08 14:56:08'),
(56,5,'Accountant','2026-09-08 14:56:08'),

(57,6,'Dean','2026-09-08 14:56:08'),
(58,6,'Department Head','2026-09-08 14:56:08'),
(59,6,'Coordinator','2026-09-08 14:56:08'),
(60,6,'Professor','2026-09-08 14:56:08'),
(61,6,'Associate Professor','2026-09-08 14:56:08'),
(62,6,'Assistant Professor','2026-09-08 14:56:08'),
(63,6,'Instructor','2026-09-08 14:56:08'),
(64,6,'Lecturer','2026-09-08 14:56:08'),
(65,6,'Staff','2026-09-08 14:56:08'),
(66,6,'Administrative Staff','2026-09-08 14:56:08')
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- 5. EMPLOYEES
-- (includes employee_portal.sql: portal_password column)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.employees (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no VARCHAR(20) NOT NULL UNIQUE,
    portal_password VARCHAR(255),
    photo_path VARCHAR(255),

    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,

    gender VARCHAR(10) NOT NULL DEFAULT 'Other'
        CHECK (gender IN ('Male', 'Female', 'Other')),
    birth_date DATE,
    contact_number VARCHAR(20),
    email VARCHAR(100),
    civil_status VARCHAR(30),
    nationality VARCHAR(50),
    religion VARCHAR(50),

    permanent_address TEXT,
    present_address TEXT,

    sss_no VARCHAR(30),
    philhealth_no VARCHAR(30),
    pagibig_no VARCHAR(30),
    tin_no VARCHAR(30),
    atm_no VARCHAR(40),

    department VARCHAR(150),
    position VARCHAR(120),
    employment_status VARCHAR(20) NOT NULL DEFAULT 'Regular'
        CHECK (employment_status IN ('Regular', 'Probationary', 'Contractual', 'Part-Time')),

    basic_salary NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    date_hired DATE,

    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(30),
    emergency_contact_address TEXT,

    dependent_name VARCHAR(100),
    dependent_relationship VARCHAR(50),
    dependent_birth_date DATE,

    education_background TEXT,
    character_reference TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_employee_department ON public.employees (department);
CREATE INDEX IF NOT EXISTS idx_employee_status ON public.employees (employment_status);
CREATE INDEX IF NOT EXISTS idx_employee_name ON public.employees (last_name, first_name);

-- employee_portal.sql equivalent: no-op on fresh installs,
-- adds the column on older databases that lack it.
ALTER TABLE public.employees
    ADD COLUMN IF NOT EXISTS portal_password VARCHAR(255);

-- SAMPLE EMPLOYEE PORTAL ACCOUNT
-- Employee No: 25-0001 / Password: Employee@123
INSERT INTO public.employees
    (employee_no, portal_password, first_name, middle_name, last_name, gender, email, department, position, employment_status, basic_salary, date_hired)
VALUES
    ('25-0001', '$2y$12$RgvcOSwmrocDtSEbbT2zFO6V5mgTwm4Q12Vj7jg5TKIAPnJ0rjngG', 'Juan', 'D.', 'Dela Cruz', 'Male', 'juan.delacruz@example.com', 'College of Computing Technology and Engineering', 'Instructor', 'Regular', 25000.00, '2026-06-01')
ON CONFLICT (employee_no) DO UPDATE
    SET portal_password = EXCLUDED.portal_password;

-- ------------------------------------------------------------
-- 6. ATTENDANCE
-- (from schema.sql + attendance_portal.sql — same definition)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance (
    attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    attendance_date DATE NOT NULL,
    time_in TIME,
    time_out TIME,
    status VARCHAR(10) NOT NULL DEFAULT 'Present'
        CHECK (status IN ('Present', 'Late', 'Absent', 'On Leave', 'Half Day')),
    remarks VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_employee_attendance_date UNIQUE (employee_id, attendance_date),
    CONSTRAINT fk_attendance_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance (attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_status ON public.attendance (status);

-- ------------------------------------------------------------
-- 7. EMPLOYEE REFERENCES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.employee_references (
    reference_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    reference_name VARCHAR(120) NOT NULL,
    reference_address TEXT,
    reference_occupation VARCHAR(100),
    reference_contact_number VARCHAR(40),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reference_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reference_employee ON public.employee_references (employee_id);

-- ------------------------------------------------------------
-- 8. PAYROLL RECORDS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payroll_records (
    payroll_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,

    period_start DATE NOT NULL,
    period_end DATE NOT NULL,

    basic_salary NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    allowances NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    other_earnings NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    deductions NUMERIC(12,2) NOT NULL DEFAULT 0.00,

    gross_pay NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    net_pay NUMERIC(12,2) NOT NULL DEFAULT 0.00,

    status VARCHAR(10) NOT NULL DEFAULT 'Draft'
        CHECK (status IN ('Draft', 'Approved', 'Paid')),
    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_payroll_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_payroll_employee ON public.payroll_records (employee_id);
CREATE INDEX IF NOT EXISTS idx_payroll_period ON public.payroll_records (period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_payroll_status ON public.payroll_records (status);

-- ------------------------------------------------------------
-- 9. updated_at auto-update triggers
-- (replaces MySQL ON UPDATE CURRENT_TIMESTAMP)
-- ------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_departments_updated_at ON public.departments;
CREATE TRIGGER trg_departments_updated_at
    BEFORE UPDATE ON public.departments
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_employees_updated_at ON public.employees;
CREATE TRIGGER trg_employees_updated_at
    BEFORE UPDATE ON public.employees
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_attendance_updated_at ON public.attendance;
CREATE TRIGGER trg_attendance_updated_at
    BEFORE UPDATE ON public.attendance
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_employee_references_updated_at ON public.employee_references;
CREATE TRIGGER trg_employee_references_updated_at
    BEFORE UPDATE ON public.employee_references
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_payroll_records_updated_at ON public.payroll_records;
CREATE TRIGGER trg_payroll_records_updated_at
    BEFORE UPDATE ON public.payroll_records
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ------------------------------------------------------------
-- 10. Sequence reset (replaces ALTER TABLE ... AUTO_INCREMENT = N)
-- Makes sure new inserts continue after the seeded IDs.
-- ------------------------------------------------------------
SELECT setval(
    pg_get_serial_sequence('public.admins', 'admin_id'),
    GREATEST(COALESCE((SELECT MAX(admin_id) FROM public.admins), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.departments', 'department_id'),
    GREATEST(COALESCE((SELECT MAX(department_id) FROM public.departments), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.positions', 'position_id'),
    GREATEST(COALESCE((SELECT MAX(position_id) FROM public.positions), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.employees', 'employee_id'),
    GREATEST(COALESCE((SELECT MAX(employee_id) FROM public.employees), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.employee_references', 'reference_id'),
    GREATEST(COALESCE((SELECT MAX(reference_id) FROM public.employee_references), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.attendance', 'attendance_id'),
    GREATEST(COALESCE((SELECT MAX(attendance_id) FROM public.attendance), 1), 1)
);
SELECT setval(
    pg_get_serial_sequence('public.payroll_records', 'payroll_id'),
    GREATEST(COALESCE((SELECT MAX(payroll_id) FROM public.payroll_records), 1), 1)
);

-- Done.
